const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (cb) => ipcRenderer.on(channel, (_e, data) => cb(data));

contextBridge.exposeInMainWorld('pet', {
  // pet window
  onEvent: on('pet-event'),
  onSettings: on('settings'),
  onSystem: on('system'),
  onCodeClip: on('code-clip'),
  onWalkDone: on('walk-done'),
  setIgnoreMouse: (ignore) => ipcRenderer.send('set-ignore-mouse', ignore),
  moveBy: (dx, dy) => ipcRenderer.send('move-by', { dx, dy }),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  walk: (dx) => ipcRenderer.send('walk', dx),
  walkStop: () => ipcRenderer.send('walk-stop'),
  fling: (vx, vy) => ipcRenderer.send('fling', { vx, vy }),
  onFlyBounce: on('fly-bounce'),
  onFlyDone: on('fly-done'),
  contextMenu: () => ipcRenderer.send('context-menu'),
  stat: (key) => ipcRenderer.send('stat', key),
  onWeather: on('weather'),
  weatherRefresh: () => ipcRenderer.invoke('weather:refresh'),
  weatherGet: () => ipcRenderer.invoke('weather:get'),

  // shared / settings window
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  hooksStatus: () => ipcRenderer.invoke('hooks:status'),
  hooksInstall: () => ipcRenderer.invoke('hooks:install'),
  hooksRemove: () => ipcRenderer.invoke('hooks:remove'),
  createShare: () => ipcRenderer.invoke('share:create'),
  trigger: (state, detail) => ipcRenderer.send('pet:trigger', { state, detail }),
  openSettings: () => ipcRenderer.send('open-settings'),
  onOpenTab: on('open-tab'),
  appInfo: () => ipcRenderer.invoke('app:info'),
  buildInstaller: () => ipcRenderer.invoke('build:installer'),
  teamGet: () => ipcRenderer.invoke('team:get'),
  teamPick: () => ipcRenderer.invoke('team:pick'),
  teamJoinCloud: (cfg) => ipcRenderer.invoke('team:join-cloud', cfg),
  teamLeave: () => ipcRenderer.invoke('team:leave'),
  teamOpen: () => ipcRenderer.invoke('team:open'),
  vault: {
    status: () => ipcRenderer.invoke('vault:status'),
    create: (pw) => ipcRenderer.invoke('vault:create', pw),
    unlock: (pw) => ipcRenderer.invoke('vault:unlock', pw),
    lock: () => ipcRenderer.invoke('vault:lock'),
    list: () => ipcRenderer.invoke('vault:list'),
    get: (id) => ipcRenderer.invoke('vault:get', id),
    save: (entry) => ipcRenderer.invoke('vault:save', entry),
    remove: (id) => ipcRenderer.invoke('vault:delete', id),
    changeMaster: (oldPw, newPw) => ipcRenderer.invoke('vault:change-master', oldPw, newPw),
    generate: (len) => ipcRenderer.invoke('vault:generate', len),
    copy: (id, field) => ipcRenderer.invoke('vault:copy', id, field),
    onLocked: on('vault-locked'),
    onState: on('vault-state'),
    onMatch: on('vault-match'),
  },
  openVault: () => ipcRenderer.send('open-vault'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  onUpdateState: on('update-state'),
  updateState: () => ipcRenderer.invoke('update:state'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  updatePick: () => ipcRenderer.invoke('update:pick'),
  updatePublish: (opts) => ipcRenderer.invoke('update:publish', opts),
});
